repos:
-   repo: local
    hooks:
    - id: nbdev_clean # hook id 
      name: nbdev clean # some readable name
      entry: nbdev_clean --fname # the actual script that gets run on the files.
#      entry: nbdev_clean --clear_all --fname # the actual script that gets run on the files
      language: system # how to run the script
      types: [jupyter] # what to run it on